<?php

namespace Nemundo\OpenSky\Com\Small;

use Nemundo\Html\Formatting\Small;

class SourceSmall extends Small
{

    public function getContent()
    {

        //"Bringing Up OpenSky: A Large-scale ADS-B Sensor Network for Research".
        $this->content= 'The OpenSky Network, https://opensky-network.org';
        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}