<?php

namespace Nemundo\OpenSky\Site;

use Nemundo\Admin\Site\AbstractKmlSite;
use Nemundo\Geo\Kml\Document\KmlDocument;
use Nemundo\Geo\Kml\Object\KmlLine;
use Nemundo\Geo\Kml\Property\AltitudeMode\AltitudeMode;
use Nemundo\OpenSky\Data\Aircraft\AircraftReader;
use Nemundo\OpenSky\Data\Tracking\TrackingReader;

class TrackingKmlSite extends AbstractKmlSite
{

    /**
     * @var TrackingKmlSite
     */
    public static $site;

    protected function loadSite()
    {
        parent::loadSite(); // TODO: Change the autogenerated stub

        TrackingKmlSite::$site = $this;

    }


    public function loadContent()
    {

        $kml = new KmlDocument();

        $aircraftReader = new AircraftReader();
        //$aircraftReader->limit= 10;
        foreach ($aircraftReader->getData() as $aircraftRow) {

            $line = new KmlLine($kml);
            $line->label = $aircraftRow->callsign;
            $line->altitudeMode=AltitudeMode::ABSOLUTE;

            $trackingReader = new TrackingReader();
            $trackingReader->filter->andEqual($trackingReader->model->aircraftId, $aircraftRow->id);
            $trackingReader->addOrder($trackingReader->model->id);
            foreach ($trackingReader->getData() as $trackingRow) {
                $line->addPoint($trackingRow->position);
            }

        }

        $kml->render();


    }

}